## 練習時間
試著使用 sklearn datasets 的其他資料集 (boston, ...)，來訓練自己的線性迴歸模型，並加上適當的正則話來觀察訓練情形。

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

In [2]:
boston = datasets.load_boston()

In [3]:
X = boston.data
Y = boston.target
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.1, random_state=4)

In [4]:
# 建立一個線性回歸模型
lasso = linear_model.Lasso(alpha=1.0)

# 將訓練資料丟進去模型訓練
lasso.fit(x_train, y_train)

# 將測試資料丟進模型得到預測結果
y_pred = lasso.predict(x_test)

In [5]:
lasso.coef_

array([-0.07256167,  0.049677  , -0.        ,  0.        , -0.        ,
        0.80504721,  0.02330318, -0.68471274,  0.26857502, -0.01526236,
       -0.71722423,  0.00834102, -0.77160917])

In [6]:
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

Mean squared error: 23.25


In [7]:
# 建立一個線性回歸模型
lasso = linear_model.Lasso(alpha=2.0)

# 將訓練資料丟進去模型訓練
lasso.fit(x_train, y_train)

# 將測試資料丟進模型得到預測結果
y_pred = lasso.predict(x_test)

In [8]:
lasso.coef_

array([-0.0244362 ,  0.03339487, -0.        ,  0.        , -0.        ,
        0.        ,  0.04644172, -0.05425583,  0.17243465, -0.01166138,
       -0.5565329 ,  0.00711839, -0.82119198])

In [9]:
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

Mean squared error: 28.50


In [10]:
# 建立一個線性回歸模型
lasso = linear_model.Lasso(alpha=0.5)

# 將訓練資料丟進去模型訓練
lasso.fit(x_train, y_train)

# 將測試資料丟進模型得到預測結果
y_pred = lasso.predict(x_test)

In [11]:
lasso.coef_

array([-0.09678854,  0.05135354, -0.        ,  0.        , -0.        ,
        2.34436856,  0.0049219 , -0.96491413,  0.28866468, -0.01571059,
       -0.74893816,  0.00965484, -0.66870041])

In [12]:
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

Mean squared error: 19.66
